# Generated by Django 5.2.6 on 2025-12-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not considered'), (1, 'Accept'), (2, 'Reject')], default=0),
        ),
    ]
