# Generated by Django 5.2.6 on 2025-12-15 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimecode',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 15, 11, 14, 47, 907560)),
        ),
    ]
