# Generated by Django 5.2.6 on 2025-12-15 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_onetimecode_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 15, 12, 35, 37, 608452)),
        ),
    ]
