# Generated by Django 5.2.6 on 2025-12-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0005_alter_onetimecode_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimecode',
            name='is_email_verified',
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
